---
title: "2018 NCAA Men’s Tournament Predictions"
author: "Bill Petti"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Predicted winners and win likelihood for all possible matchups in the 2018 NCAA Men's Basketball Tournament. Predictions generated on Monday, 3-12-2018.

```{r, echo=FALSE, warning=FALSE, message=FALSE}
require(DT)
require(dplyr)
require(readr)

combine_lower_higher <- read_csv("/Users/williampetti/predicting-march-madness/combine_lower_higher.csv")

table_to_display <- combine_lower_higher %>%
  dplyr::mutate(win_likelihood = round(win_likelihood, 3)) %>%
  dplyr::rename(`Team` = team1, 
         `Opponent` = team2, 
         `Seed` = team1_seed, 
         `Opponent Seed` = team2_seed,
         `Predicted Winner` = predicted_winner, 
         `Likelihood of Win` = win_likelihood)
```
```{r, echo=FALSE}
DT::datatable(table_to_display, filter = "top",
              options = list(
                columnDefs = list(list(className = 'dt-center', targets = 1:5)),
                pageLength = 70,
                lengthMenu = c(10, 20, 50, 70, 5000)))
```
